name: Deploy Nismara Transport to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js Project
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DISCORD_LOG_WEBHOOK_URL: ${{ secrets.DISCORD_LOG_WEBHOOK_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          TRUCKY_API_KEY: ${{ secrets.TRUCKY_API_KEY }}
          TRUCKY_COMPANY_ID: ${{ secrets.TRUCKY_COMPANY_ID }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          NEXT_PUBLIC_R2_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_R2_PUBLIC_URL }}
          MIDTRANS_SERVER_KEY: ${{ secrets.MIDTRANS_SERVER_KEY }}
          NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY }}
        run: npm run build

      - name: Compress Build Files
        run: tar -czvf deploy.tar.gz .next public

      - name: Copy Files to VPS via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "deploy.tar.gz"
          target: "/root/website"

      - name: Execute Remote SSH to Extract & Restart PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            source ~/.bashrc || true
            source ~/.profile || true

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd /root/website

            git pull origin main

            if [ -f deploy.tar.gz ]; then
              tar -xzvf deploy.tar.gz
              rm deploy.tar.gz
            fi

            # Install npm khusus untuk production (menghemat memori)
            npm install --production

            # Restart PM2 atau jalankan untuk pertama kali
            pm2 restart nismara-web || pm2 start npm --name "nismara-web" -- start
